# This is a sample build configuration for Java.
# Do not use tabs to indent your configuration.
# You can specify a custom docker image from Dockerhub
# for your build environment.
pipeline:
    - job:
        script: # Modify the commands below to build your repository.
            - docker build -t jainishshah17/bitbucket-jfrog .
            - docker images
            - ls
            - pwd